### ISSUE TITLE
Error during build:  Server is not running.

### ISSUE THREAD

**Issue by caboe** [nuxt/sigma-demo#2]
Hello,

I just checked out the project and tried to build it. Unfortunately it runs into an error.

**Versions**
MacOS 10.15.7
Node v14.12.0
Yarn 1.22.4

**Steps to reproduce**
Check out latest version
Run yarn
Run yarn build

**What is expected**
Build without errors

**What is actual happening**
Process throws error:
`✔ Ready to run node .output/server                                                                                                                                                                                           20:32:08

 FATAL  Server is not running.                                                                                                                                                                                               20:32:08

  at Server.close (net.js:1605:12)
  at Object.onceWrapper (events.js:420:28)
  at Server.emit (events.js:314:20)
  at Server.EventEmitter.emit (domain.js:486:12)
  at emitCloseNT (net.js:1658:8)
  at processTicksAndRejections (internal/process/task_queues.js:79:21)
`

yarn dev runs without any problems...

Thanks for this great approach, to make it possible to run nuxt on Cloudflare workers...
Carsten

**Comment by danielroe** [comment]
@caboe Great to hear you're looking forward to this. This is a demo repository for a yet-to-be-released project. Rest assured, there will be documentation when it is released. 🙃

**Comment by caboe** [comment]
@danielroe Found the problem: I pulled a non-working version (0.46). After I updated (0.60), everything works as expected.
